/* Sprocket Manifest
 *= require Panel
 *= require Typify
 */
var Icon = Panel.extend(
    /** @lends Icon# */
    {
      /**
       * Extends the Panel constructor to modify the behavior when a string is passed in as attributes.
       * Instead of applying the string to the body, it will instead be used as the type.
       * @class
       * The Icon class provides a simple accessor to the many FontAwesome icons provided.
       * It is the only Component that does not wrap its body.
       *
       * @extends Panel
       * @constructs Icon
       *
       * @param {Object} [attributes={}]  Values to apply to this object.  All values supplied are applied to the created object
       * @param {Object} [options={}]     Passed to the initialize function (currently unused by any default component)
       */
      constructor : function(attributes, options) {
        if(typeof(attributes) == "string") {
          attributes = {type: attributes};
        }

        Icon.__super__.constructor.call(this, attributes, options);
      },

      initialize : function(args) {
        Icon.__super__.initialize.call(this, args);

        this.base = "icon";

        Typify(this);
      },

      template : _.template("<i <%= rootAttrs %>></i> <%= yield %>")
    },
    /** @lends Icon */
    {
      klass: "Icon",
      types: [
              // Web Application Icons
              "adjust",
              "anchor",
              "asterisk",
              "ban-circle",
              "bar-chart",
              "barcode",
              "beaker",
              "beer",
              "bell-alt",
              "bell",
              "bolt",
              "book",
              "bookmark-empty",
              "bookmark",
              "briefcase",
              "bullhorn",
              "bullseye",
              "calendar-empty",
              "calendar",
              "camera-retro",
              "camera",
              "certificate",
              "check-empty",
              "check-minus",
              "check-sign",
              "check",
              "circle-blank",
              "circle",
              "cloud-download",
              "cloud-upload",
              "cloud",
              "code-fork",
              "code",
              "coffee",
              "cog",
              "cogs",
              "collapse-alt",
              "comment-alt",
              "comment",
              "comments-alt",
              "comments",
              "credit-card",
              "crop",
              "dashboard",
              "desktop",
              "download-alt",
              "download",
              "edit-sign",
              "edit",
              "ellipsis-horizontal",
              "ellipsis-vertical",
              "envelope-alt",
              "envelope",
              "eraser",
              "exchange",
              "exclamation-sign",
              "exclamation",
              "expand-alt",
              "external-link-sign",
              "external-link",
              "eye-close",
              "eye-open",
              "facetime-video",
              "fighter-jet",
              "film",
              "filter",
              "fire-extinguisher",
              "fire",
              "flag-alt",
              "flag-checkered",
              "flag",
              "folder-close-alt",
              "folder-close",
              "folder-open-alt",
              "folder-open",
              "food",
              "frown",
              "gamepad",
              "gift",
              "glass",
              "globe",
              "group",
              "hdd",
              "headphones",
              "heart-empty",
              "heart",
              "home",
              "inbox",
              "info-sign",
              "info",
              "key",
              "keyboard",
              "laptop",
              "leaf",
              "legal",
              "lemon",
              "level-down",
              "level-up",
              "lightbulb",
              "location-arrow",
              "lock",
              "magic",
              "magnet",
              "mail-forward (alias)",
              "mail-reply (alias)",
              "mail-reply-all (alias)",
              "map-marker",
              "meh",
              "microphone-off",
              "microphone",
              "minus-sign-alt",
              "minus-sign",
              "minus",
              "mobile-phone",
              "money",
              "move",
              "music",
              "off",
              "ok-circle",
              "ok-sign",
              "ok",
              "pencil",
              "phone-sign",
              "phone",
              "picture",
              "plane",
              "plus-sign",
              "plus",
              "print",
              "pushpin",
              "puzzle-piece",
              "qrcode",
              "question-sign",
              "question",
              "quote-left",
              "quote-right",
              "random",
              "refresh",
              "remove-circle",
              "remove-sign",
              "remove",
              "reorder",
              "reply-all",
              "reply",
              "resize-horizontal",
              "resize-vertical",
              "retweet",
              "road",
              "rocket",
              "rotate-left (alias)",
              "rotate-right (alias)",
              "rss-sign",
              "rss",
              "screenshot",
              "search",
              "share-alt",
              "share-sign",
              "share",
              "shield",
              "shopping-cart",
              "sign-blank",
              "signal",
              "signin",
              "signout",
              "sitemap",
              "smile",
              "sort-down",
              "sort-up",
              "sort",
              "spinner",
              "star-empty",
              "star-half-full (alias)",
              "star-half-empty",
              "star-half",
              "star",
              "tablet",
              "tag",
              "tags",
              "tasks",
              "terminal",
              "thumbs-down",
              "thumbs-up",
              "ticket",
              "time",
              "tint",
              "trash",
              "trophy",
              "truck",
              "umbrella",
              "unlock-alt",
              "unlock",
              "upload-alt",
              "upload",
              "user-md",
              "user",
              "volume-down",
              "volume-off",
              "volume-up",
              "warning-sign",
              "wrench",
              "zoom-in",
              "zoom-out",

              // Text Editor Icons
              "file",
              "file-alt",
              "cut",
              "copy",
              "paste",
              "save",
              "undo",
              "repeat",
              "text-height",
              "text-width",
              "align-left",
              "align-center",
              "align-right",
              "align-justify",
              "indent-left",
              "indent-right",
              "font",
              "bold",
              "italic",
              "strikethrough",
              "underline",
              "superscript",
              "subscript",
              "link",
              "unlink",
              "paper-clip",
              "eraser",
              "columns",
              "table",
              "th-large",
              "th",
              "th-list",
              "list",
              "list-ol",
              "list-ul",
              "list-alt",

              // Directional Icons
              "angle-left",
              "angle-right",
              "angle-up",
              "angle-down",
              "arrow-down",
              "arrow-left",
              "arrow-right",
              "arrow-up",
              "caret-down",
              "caret-left",
              "caret-right",
              "caret-up",
              "chevron-down",
              "chevron-left",
              "chevron-right",
              "chevron-up",
              "chevron-sign-left",
              "chevron-sign-right",
              "chevron-sign-up",
              "chevron-sign-down",
              "circle-arrow-down",
              "circle-arrow-left",
              "circle-arrow-right",
              "circle-arrow-up",
              "double-angle-left",
              "double-angle-right",
              "double-angle-up",
              "double-angle-down",
              "hand-down",
              "hand-left",
              "hand-right",
              "hand-up",

              // Video Player Icons
              "play-circle",
              "play-sign",
              "play",
              "pause",
              "stop",
              "eject",
              "backward",
              "forward",
              "fast-backward",
              "fast-forward",
              "step-backward",
              "step-forward",
              "fullscreen",
              "resize-full",
              "resize-small",

              // Brand Icons
              "css3",
              "facebook",
              "facebook-sign",
              "twitter",
              "twitter-sign",
              "github",
              "github-sign",
              "html5",
              "linkedin",
              "linkedin-sign",
              "maxcdn",
              "pinterest",
              "pinterest-sign",
              "google-plus",
              "google-plus-sign",

              // Medical Icons
              "ambulance",
              "beaker",
              "h-sign",
              "hospital",
              "medkit",
              "plus-sign-alt",
              "stethoscope",
              "user-md"
            ]
    });